esphome:
  name: garage-door
  friendly_name: Garage Door
  area: Garage
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
  on_boot:
    - priority: 600
      then:
        - switch.turn_off:
            id: relay

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  # TODO: secrets
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret static_ip
    gateway: !secret gateway_ip
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret fallback_ap_ssid
    password: !secret fallback_ap_password

captive_portal:

# TODO potentially add door position sensors, or find a way to query MyQ for door state
cover:
  - platform: template
    name: None
    device_class: garage
    icon: "mdi:garage"
    open_action:
      - switch.turn_on:
          id: relay
    close_action:
      - switch.turn_on:
          id: relay
    stop_action:
      - switch.turn_on:
          id: relay
    toggle_action:
      - switch.turn_on:
          id: relay
    optimistic: true
    assumed_state: true

switch:
  - platform: gpio
    disabled_by_default: true
    pin: GPIO10
    id: relay
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 500ms
      - switch.turn_off: relay
